import json

def c(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}
def md(src): return {"cell_type":"markdown","metadata":{},"source":src}

# ── Cell sources defined as lists of lines ──────────────────────────────────

CELL_CONFIG = [
    "import asyncio, json, os, re, traceback\n",
    "import asyncpg, litellm, openpyxl\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import unicodedata\n",
    "\n",
    "DB_DSN    = 'postgresql://postgres:postgres123@192.168.1.229:5432/lumina_driver_dev'\n",
    "XLSX_PATH = 'uploads/2026/03/97fb555d-8c66-47b5-914b-b81f81c3d813.xlsx'\n",
    "\n",
    "_PREFIXES = {'openai':'','azure':'azure/','anthropic':'anthropic/','google':'gemini/','ollama':'ollama/'}\n",
    "def build_model(p, m):\n",
    "    px = _PREFIXES.get(p, '')\n",
    "    return m if (px and m.startswith(px)) else f'{px}{m}'\n",
    "\n",
    "async def _load_cfg(purpose):\n",
    "    conn = await asyncpg.connect(DB_DSN)\n",
    "    row  = await conn.fetchrow(\n",
    "        'SELECT provider,model_name,api_key,base_url,extra_config FROM core_aimodelconfig'\n",
    "        ' WHERE purpose=$1 AND is_default=TRUE AND is_active=TRUE LIMIT 1', purpose)\n",
    "    await conn.close()\n",
    "    raw   = row['extra_config']\n",
    "    extra = json.loads(raw) if raw and raw != 'null' else {}\n",
    "    return {'model': build_model(row['provider'], row['model_name']),\n",
    "            'api_key': row['api_key'], 'api_base': row['base_url'], **extra}\n",
    "\n",
    "chat_cfg  = await _load_cfg('chat')\n",
    "embed_cfg = await _load_cfg('embedding')\n",
    "if 'azure/' in chat_cfg['model']:  os.environ['AZURE_API_VERSION'] = '2024-12-01-preview'\n",
    "if 'azure/' in embed_cfg['model']: os.environ['AZURE_API_VERSION'] = '2024-12-01-preview'\n",
    "print('Chat :', chat_cfg['model'])\n",
    "print('Embed:', embed_cfg['model'])\n",
]

CELL_PARSE_HELPERS = [
    "# ── openpyxl helpers ────────────────────────────────────────────────────\n",
    "\n",
    "def get_merged_val(ws, row, col, merged):\n",
    "    for r in merged:\n",
    "        if r.min_row <= row <= r.max_row and r.min_col <= col <= r.max_col:\n",
    "            return ws.cell(r.min_row, r.min_col).value\n",
    "    return None\n",
    "\n",
    "def has_border(cell):\n",
    "    b = cell.border\n",
    "    return any(getattr(b, s).style for s in ('top','bottom','left','right'))\n",
    "\n",
    "def find_header_start(ws, n_cols, max_check=30):\n",
    "    for rn in range(1, max_check+1):\n",
    "        if sum(1 for c in range(1, min(n_cols+1,15)) if has_border(ws.cell(rn,c))) >= 3:\n",
    "            return rn\n",
    "    return 1\n",
    "\n",
    "def find_data_start(ws, merged):\n",
    "    for rn in range(1, ws.max_row+1):\n",
    "        v = ws.cell(rn,1).value or get_merged_val(ws,rn,1,merged)\n",
    "        if v is None: continue\n",
    "        s = str(v).strip()\n",
    "        if not s or s == 'nan': continue\n",
    "        try: float(s); continue\n",
    "        except (ValueError, TypeError): pass\n",
    "        if s == s.upper() and len(s) > 1: continue\n",
    "        return rn\n",
    "    return 1\n",
    "\n",
    "def fill_nearest(values):\n",
    "    result = list(values)\n",
    "    pos = [i for i,v in enumerate(result) if v is not None]\n",
    "    if not pos: return result\n",
    "    first, last = pos[0], pos[-1]\n",
    "    for i in range(first, last+1):\n",
    "        if result[i] is not None: continue\n",
    "        lp = max((p for p in pos if p < i), default=None)\n",
    "        rp = min((p for p in pos if p > i), default=None)\n",
    "        if lp is not None and rp is not None:\n",
    "            result[i] = result[lp] if (i-lp) < (rp-i) else result[rp]\n",
    "        elif lp is not None: result[i] = result[lp]\n",
    "        elif rp is not None: result[i] = result[rp]\n",
    "    return result\n",
    "\n",
    "def get_n_cols(xlsx_path, sheet_name, nrows=20):\n",
    "    df = pd.read_excel(xlsx_path, sheet_name=sheet_name, header=None, nrows=nrows)\n",
    "    return df.dropna(axis=1, how='all').shape[1]\n",
    "\n",
    "def build_headers(ws, h_start, d_start, n_cols, merged):\n",
    "    filled = []\n",
    "    for rn in range(h_start, d_start):\n",
    "        vals = []\n",
    "        for cn in range(1, n_cols+1):\n",
    "            v = ws.cell(rn,cn).value\n",
    "            if v is None: v = get_merged_val(ws,rn,cn,merged)\n",
    "            vals.append(str(v).strip() if v is not None else None)\n",
    "        filled.append(fill_nearest(vals))\n",
    "    hdrs = []\n",
    "    for ci in range(n_cols):\n",
    "        parts = []\n",
    "        for rv in filled:\n",
    "            v = rv[ci]\n",
    "            if v and v not in ('nan','None') and v not in parts: parts.append(v)\n",
    "        hdrs.append('-'.join(parts) if parts else f'COL_{ci}')\n",
    "    return hdrs\n",
    "\n",
    "def load_sheet_raw(wb, xlsx_path, sheet_name):\n",
    "    ws = wb[sheet_name]\n",
    "    merged  = list(ws.merged_cells.ranges)\n",
    "    n_cols  = get_n_cols(xlsx_path, sheet_name)\n",
    "    d_start = find_data_start(ws, merged)\n",
    "    h_start = find_header_start(ws, n_cols)\n",
    "    headers = build_headers(ws, h_start, d_start, n_cols, merged)\n",
    "    rows, bolds = [], []\n",
    "    for rn in range(d_start, ws.max_row+1):\n",
    "        row = []\n",
    "        for cn in range(1, n_cols+1):\n",
    "            v = ws.cell(rn,cn).value\n",
    "            if v is None: v = get_merged_val(ws,rn,cn,merged)\n",
    "            row.append(v)\n",
    "        rows.append(row)\n",
    "        bolds.append(ws.cell(rn,1).font.bold or False)\n",
    "    df = pd.DataFrame(rows, columns=headers)\n",
    "    df = df.dropna(axis=1, how='all')\n",
    "    fc = df.columns[0]\n",
    "    mask = df[fc].notna() & df[fc].astype(str).str.strip().ne('')\n",
    "    df   = df[mask].reset_index(drop=True)\n",
    "    bolds = [bolds[i] for i,m in enumerate(mask) if m]\n",
    "    return df, bolds, headers\n",
    "\n",
    "wb = openpyxl.load_workbook(XLSX_PATH, data_only=True)\n",
    "print('Sheets:', wb.sheetnames)\n",
]

CELL_LLM_SCHEMA = [
    "def build_preview_text(df, bolds, headers, n_rows=10, n_cols=10):\n",
    "    cols = headers[:n_cols]\n",
    "    lines = ['  '.join(f'{h[:16]:16s}' for h in cols)]\n",
    "    lines.append('-' * (18 * min(n_cols, len(cols))))\n",
    "    for i, (_, row) in enumerate(df.iterrows()):\n",
    "        if i >= n_rows: break\n",
    "        prefix = '[BOLD] ' if (i < len(bolds) and bolds[i]) else '       '\n",
    "        cells  = '  '.join(f'{str(row.iloc[j])[:16]:16s}' for j in range(min(n_cols, len(df.columns))))\n",
    "        lines.append(prefix + cells)\n",
    "    return '\\n'.join(lines)\n",
    "\n",
    "\n",
    "JSON_SCHEMA_TEMPLATE = '''\n",
    "{\n",
    '  \"sheet_description\": \"mo ta ngan sheet chua gi\",\n',
    '  \"row_structure\": \"mo ta parent la gi, sub-category la gi (null neu khong co hierarchy)\",\n',
    '  \"has_hierarchy\": true,\n',
    '  \"key_columns\": {\n',
    '    \"entity_name\": \"ten cot chua ten chinh (store/entity)\",\n',
    '    \"category\": \"ten cot sub-category hoac null\",\n',
    '    \"main_value\": \"ten cot gia tri chinh quan trong nhat\",\n',
    '    \"target\": \"ten cot ke hoach/target hoac null\",\n',
    '    \"prev_period\": \"ten cot ky truoc hoac null\"\n',
    '  },\n',
    '  \"parent_detection\": \"bold=True\"\n',
    "}\n",
    "'''\n",
    "\n",
    "\n",
    "def llm_parse_schema(chat_cfg, sheet_name, headers, preview_text):\n",
    "    prompt = (\n",
    "        f'Ban la data analyst. Sheet Excel \"{sheet_name}\".\\n'\n",
    "        'Dong [BOLD] la parent row (vi du ten cua hang), khong bold la sub-category.\\n\\n'\n",
    "        f'Headers (first 15):\\n{json.dumps(headers[:15], ensure_ascii=False)}\\n\\n'\n",
    "        f'Preview:\\n{preview_text}\\n\\n'\n",
    "        'Tra ve JSON format (CHI JSON, khong giai thich):\\n'\n",
    "        + JSON_SCHEMA_TEMPLATE\n",
    "    )\n",
    "    kw   = {k:v for k,v in chat_cfg.items() if k != 'model' and v is not None}\n",
    "    resp = litellm.completion(\n",
    "        model=chat_cfg['model'],\n",
    "        messages=[{'role':'user','content':prompt}],\n",
    "        temperature=0, **kw)\n",
    "    raw = resp.choices[0].message.content.strip()\n",
    "    if raw.startswith('```'):\n",
    "        raw = raw.split('```')[1]\n",
    "        if raw.startswith('json'): raw = raw[4:]\n",
    "    try:\n",
    "        return json.loads(raw.strip())\n",
    "    except json.JSONDecodeError:\n",
    "        return {'sheet_description': sheet_name, 'has_hierarchy': False,\n",
    "                'row_structure': '', 'key_columns': {}, 'parent_detection': 'bold=True'}\n",
    "\n",
    "\n",
    "# Parse schema cho tất cả sheets\n",
    "all_schemas = {}\n",
    "all_dfs     = {}\n",
    "all_bolds   = {}\n",
    "\n",
    "for sheet_name in wb.sheetnames:\n",
    "    print(f'\\n=== {sheet_name} ===')\n",
    "    try:\n",
    "        df, bolds, headers = load_sheet_raw(wb, XLSX_PATH, sheet_name)\n",
    "        preview = build_preview_text(df, bolds, headers)\n",
    "        schema  = llm_parse_schema(chat_cfg, sheet_name, headers, preview)\n",
    "        all_schemas[sheet_name] = schema\n",
    "        all_dfs[sheet_name]     = df\n",
    "        all_bolds[sheet_name]   = bolds\n",
    "        print(f'  rows={len(df)} cols={len(df.columns)}')\n",
    "        print(f'  desc: {schema.get(\"sheet_description\",\"\")[:80]}')\n",
    "        print(f'  hierarchy: {schema.get(\"has_hierarchy\")} | entity_col: {schema.get(\"key_columns\",{}).get(\"entity_name\",\"\")[:40]}')\n",
    "    except Exception as e:\n",
    "        print(f'  ERROR: {e}')\n",
    "\n",
    "print(f'\\nDone: {len(all_schemas)}/{len(wb.sheetnames)} sheets parsed')\n",
]

CELL_ADD_HIERARCHY = [
    "def add_hierarchy_cols(df, bolds, schema):\n",
    "    kc = schema.get('key_columns', {})\n",
    "    entity_col = kc.get('entity_name', df.columns[0])\n",
    "    has_hier   = schema.get('has_hierarchy', False)\n",
    "    if entity_col not in df.columns:\n",
    "        entity_col = df.columns[0]\n",
    "    if not has_hier:\n",
    "        df = df.copy()\n",
    "        df.insert(0, '__store__',    df[entity_col].astype(str))\n",
    "        df.insert(1, '__category__', None)\n",
    "        return df\n",
    "    current, stores, cats = None, [], []\n",
    "    for i, (_, row) in enumerate(df.iterrows()):\n",
    "        bold = bolds[i] if i < len(bolds) else False\n",
    "        val  = str(row[entity_col]).strip()\n",
    "        if bold:\n",
    "            current = val\n",
    "            stores.append(val)\n",
    "            cats.append(None)\n",
    "        else:\n",
    "            stores.append(current)\n",
    "            cats.append(val)\n",
    "    df = df.copy()\n",
    "    df.insert(0, '__store__',    stores)\n",
    "    df.insert(1, '__category__', cats)\n",
    "    return df\n",
    "\n",
    "\n",
    "dfs = {}\n",
    "for name, df in all_dfs.items():\n",
    "    dfs[name] = add_hierarchy_cols(df, all_bolds[name], all_schemas[name])\n",
    "    print(f'{name!r}: {dfs[name].shape}  cats={dfs[name][\"__category__\"].dropna().unique()[:3].tolist()}')\n",
]

CELL_EMBED_SCHEMAS = [
    "# Embed schema descriptions cho semantic routing\n",
    "schema_texts = [\n",
    "    f'Sheet: {n}\\n'\n",
    "    f'Description: {all_schemas[n].get(\"sheet_description\",\"\")}\\n'\n",
    "    f'Columns: {list(all_dfs[n].columns[:10])}\\n'\n",
    "    f'Entity: {all_schemas[n].get(\"key_columns\",{}).get(\"entity_name\",\"\")}'\n",
    "    for n in wb.sheetnames if n in all_schemas\n",
    "]\n",
    "sheet_names_ordered = [n for n in wb.sheetnames if n in all_schemas]\n",
    "\n",
    "kw_e = {k:v for k,v in embed_cfg.items() if k != 'model' and v is not None}\n",
    "resp_e = litellm.embedding(model=embed_cfg['model'], input=schema_texts, **kw_e)\n",
    "schema_embeddings = np.array([item['embedding'] for item in resp_e.data])\n",
    "print(f'Schema embeddings: {schema_embeddings.shape}')\n",
    "\n",
    "def find_relevant_sheets(question, top_k=2):\n",
    "    kw = {k:v for k,v in embed_cfg.items() if k != 'model' and v is not None}\n",
    "    r  = litellm.embedding(model=embed_cfg['model'], input=[question], **kw)\n",
    "    q  = np.array(r.data[0]['embedding'])\n",
    "    norms = np.linalg.norm(schema_embeddings, axis=1) * np.linalg.norm(q)\n",
    "    sims  = schema_embeddings @ q / np.where(norms==0, 1e-9, norms)\n",
    "    top   = np.argsort(sims)[::-1][:top_k]\n",
    "    return [(sheet_names_ordered[i], float(sims[i])) for i in top]\n",
    "\n",
    "# Test routing\n",
    "for q in [\n",
    "    'Doanh thu cua hang 98 Nguyen Van Troi thang 1?',\n",
    "    'Banh huy cong ty thang 1?',\n",
    "    'So sanh doanh thu Noel nam nay voi nam ngoai?',\n",
    "]:\n",
    "    hits = find_relevant_sheets(q, top_k=2)\n",
    "    print(f'Q: {q}')\n",
    "    for n, s in hits: print(f'  -> {n!r}  {s:.3f}')\n",
]

CELL_ANSWER = [
    "def norm(s):\n",
    "    return unicodedata.normalize('NFD', str(s)).encode('ascii','ignore').decode().lower()\n",
    "\n",
    "\n",
    "def answer(question, top_k=2):\n",
    "    relevant = find_relevant_sheets(question, top_k)\n",
    "    print(f'Sheets: {[(n, f\"{s:.3f}\") for n,s in relevant]}')\n",
    "\n",
    "    # Build context\n",
    "    ctx_parts = []\n",
    "    for sheet_name, _ in relevant:\n",
    "        schema = all_schemas[sheet_name]\n",
    "        df     = dfs[sheet_name]\n",
    "        kc     = schema.get('key_columns', {})\n",
    "        ctx_parts.append(\n",
    "            f'### dfs[\"{sheet_name}\"]\\n'\n",
    "            f'Shape: {df.shape}\\n'\n",
    "            f'Desc: {schema.get(\"sheet_description\",\"\")}\\n'\n",
    "            f'Structure: {schema.get(\"row_structure\",\"\")}\\n'\n",
    "            f'Key cols: entity={kc.get(\"entity_name\",\"\")} | '\n",
    "            f'main_value={kc.get(\"main_value\",\"\")} | target={kc.get(\"target\",\"\")}\\n'\n",
    "            f'Columns (first 12): {list(df.columns[:12])}\\n'\n",
    "            f'Sample (3 rows):\\n{df[[\"__store__\",\"__category__\"]].head(3).to_string(index=False)}'\n",
    "        )\n",
    "    ctx = '\\n\\n'.join(ctx_parts)\n",
    "\n",
    "    prompt = (\n",
    "        'Ban la data analyst. Du lieu la dict `dfs` chua pandas DataFrame, '\n",
    "        'moi key la ten sheet.\\n\\n'\n",
    "        f'{ctx}\\n\\n'\n",
    "        f'Cau hoi: {question}\\n\\n'\n",
    "        'Quy tac:\\n'\n",
    "        '- Chi tra ve Python code thuan, KHONG markdown\\n'\n",
    "        '- Gan ket qua vao bien `result`\\n'\n",
    "        '- __store__: ten entity chinh (propagated tu parent bold rows)\\n'\n",
    "        '- __category__: sub-category (None neu la parent row)\\n'\n",
    "        '- Filter ten: dung str.contains(..., case=False, na=False)\\n'\n",
    "        '- De normalize tieng Viet: dung ham norm() da co san\\n'\n",
    "        '  VD: df[df[\"__store__\"].map(norm).str.contains(norm(\"Nguyen Van Troi\"))]\\n'\n",
    "        '- KHONG import them thu vien'\n",
    "    )\n",
    "    kw   = {k:v for k,v in chat_cfg.items() if k != 'model' and v is not None}\n",
    "    resp = litellm.completion(\n",
    "        model=chat_cfg['model'],\n",
    "        messages=[{'role':'user','content':prompt}],\n",
    "        temperature=0, **kw)\n",
    "    code = resp.choices[0].message.content.strip()\n",
    "    for pat in [r'^```python\\n?', r'^```\\n?', r'\\n?```$']:\n",
    "        code = re.sub(pat, '', code)\n",
    "    print(f'Code:\\n{code}\\n')\n",
    "    local = {'dfs': dfs, 'pd': pd, 'np': np, 'norm': norm}\n",
    "    try:\n",
    "        exec(code, {}, local)\n",
    "        raw = local.get('result')\n",
    "    except Exception:\n",
    "        return traceback.format_exc()\n",
    "\n",
    "    # Format answer\n",
    "    result_str = raw.to_string(index=False) if isinstance(raw, pd.DataFrame) else str(raw)\n",
    "    resp2 = litellm.completion(\n",
    "        model=chat_cfg['model'],\n",
    "        messages=[{'role':'user','content':\n",
    "            f'Cau hoi: {question}\\nKet qua: {result_str}\\n'\n",
    "            'Tra loi tieng Viet, ngan gon. So tien format X.XXX.XXX VND.'}],\n",
    "        temperature=0.3, **kw)\n",
    "    return resp2.choices[0].message.content.strip()\n",
    "\n",
    "print('answer() ready')\n",
]

CELL_Q1 = [
    "q = 'Doanh thu thuc hien thang 1/2026 cua cua hang 98 Nguyen Van Troi la bao nhieu?'\n",
    "print('Q:', q)\n",
    "print('='*60)\n",
    "print(answer(q))\n",
]

CELL_Q2 = [
    "q = 'Top 3 cua hang co doanh thu Banh cao nhat thang 1?'\n",
    "print('Q:', q)\n",
    "print('='*60)\n",
    "print(answer(q))\n",
]

CELL_Q3 = [
    "q = 'Tong banh huy cong ty thang 1/2026 la bao nhieu?'\n",
    "print('Q:', q)\n",
    "print('='*60)\n",
    "print(answer(q))\n",
]

CELL_Q4 = [
    "q = 'So sanh doanh thu Noel nam nay voi nam ngoai, cua hang nao tang truong tot nhat?'\n",
    "print('Q:', q)\n",
    "print('='*60)\n",
    "print(answer(q))\n",
]

# ── Build notebook ───────────────────────────────────────────────────────────

cells = [
    md("# Full Excel RAG — LLM Schema Parsing + Text-to-Pandas\n\n"
       "Flow: tất cả sheets → LLM parse schema từng sheet → semantic routing → Text-to-Pandas agent"),
    c(CELL_CONFIG),
    c(CELL_PARSE_HELPERS),
    c(CELL_LLM_SCHEMA),
    c(CELL_ADD_HIERARCHY),
    c(CELL_EMBED_SCHEMAS),
    c(CELL_ANSWER),
    c(CELL_Q1),
    c(CELL_Q2),
    c(CELL_Q3),
    c(CELL_Q4),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
        "language_info": {"name":"python","version":"3.12.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open("test_full_excel_rag.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print("Written: test_full_excel_rag.ipynb")
